/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yangsen_curl_Curl */

#ifndef _Included_com_yangsen_curl_Curl
#define _Included_com_yangsen_curl_Curl
#ifdef __cplusplus
extern "C" {
#endif

#ifndef BYTE
typedef const char BYTE;
typedef char* LPBYTE;
#endif

typedef struct CURLUploadInfo {
    long bytesRead;
    LPBYTE data;
} CURLUploadInfo, *LPCURLUploadInfo;

/*
 * Class:     com_yangsen_curl_Curl
 * Method:    globalInit
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_qiniu_client_curl_Curl_globalInit(JNIEnv *, jobject);

/*
 * Class:     com_yangsen_curl_Curl
 * Method:    request
 * Signature: (Ljava/lang/Object;Ljava/lang/String;J[Ljava/lang/Object;[B)J
 */
JNIEXPORT void JNICALL Java_com_qiniu_client_curl_Curl_requestNative(JNIEnv *, jobject, jobject curlRequest, jobject configure, jobject curlHandler);

#ifdef __cplusplus
}
#endif
#endif
